### PR TITLE
Refactor/optimized deploy

### LINKED ISSUE #15: Drive Base
### 🚀 Summary:

Code Swerve Drive... reuse 2023 code. If phoenix6 api is not compatible use phoenix 5 and create new issue to update the firmware on the TalonFX (if possible).

### 📋 Tasks:

- [ ] Recover 2023 Swerve Drive
- [ ] Convert from ctre to phoenix5 or phoenix 6 api as needed.
- [ ] Make open loop control functional
- [ ] Recalibrate motor controllers with 2024 base.

### PR DESCRIPTION
**Pull request by NathanGrenier**
### 🛠 Proposed Changes:

Fixed swerve drive calibration and optimized files being deployed to the RIO.

### 📝 Details:

- Removed code calibration of swerve module offsets.
- Moved all code that needs to be deployed to `/src`

### 🔗 Related Issue(s):

- Resolves #15 (Not sure if it fully resolves this issue)

### CODE REVIEW

**Comment by NathanGrenier** [comment]
This branch still needs it's swerve code refactored (lots of unused code and comments)

**Comment by NathanGrenier** [comment]
There seems to be a bug with the basic pyfrc tests. The action will run the `test` step forever.

image

I've also encountered this bug when deploying to the physical bot. For now, I've just disabled the test by commenting them out. If you want to deploy and not get prompted to re-import the test (which is the default behavior), you can add `--skip-tests` to the robotpy deploy command.

**Comment by Portnord** [comment]
> There seems to be a bug with the basic pyfrc tests. The action will run the `test` step forever.
> 
> image
> 
> I've also encountered this bug when deploying to the physical bot. For now, I've just disabled the test by commenting them out. If you want to deploy and not get prompted to re-import the test (which is the default behavior), you can add `--skip-tests` to the robotpy deploy command.

How long did you wait? That last test_practice apparently runs through an entire practice match, so it would take at least 3 and a half minutes.

**Comment by NathanGrenier** [comment]
> How long did you wait? That last test_practice apparently runs through an entire practice match, so it would take at least 3 and a half minutes.

The runner was alive for ~5 minutes.

**Comment by Portnord** [comment]
> > How long did you wait? That last test_practice apparently runs through an entire practice match, so it would take at least 3 and a half minutes.
> 
> The runner was alive for ~5 minutes.
> 
> Can you link where you read that the test runs through an entire game?

https://robotpy.readthedocs.io/projects/pyfrc/en/stable/testing.html#pyfrc.tests.basic.test_practice

Instead of loading by skipping tests can we include the one dummy test that does something like 'assert True'? It doesn't run the robot so it shouldn't hang any servers, but it would leave the hook in the folder structure to add testing later.

**Comment by NathanGrenier** [comment]
> Instead of loading by skipping tests can we include the one dummy test that does something like 'assert True'? It doesn't run the robot so it shouldn't hang any servers, but it would leave the hook in the folder structure to add testing later.

I tried that (I already had a sample test) and it still hung indefinitely.

**Comment by Portnord** [comment]
Applied these changes manually to feature/drivebase, tested and merged. This branch and pull request are no longer needed.

**Pull request closed without merging**
